[package]
name = "disrupt_compose"
version = "0.1.0"
authors = ["DrTexx <23412100+DrTexx@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
